### ISSUE TITLE
Guardar / Mostar profile Pic

### ISSUE THREAD

**Issue by bcarvalheiro** [bcarvalheiro/DjangoParte1#1]
Estou com dificuldade em mostrar ou guardar as profile pics dos users. Aliás, já está muita  coisa feita, o unico problema é que não consigo despistar se está a funcionar ou não. Vejam o que conseguem fazer.
O que eu já tentei, ou que acho que poderia estar errado ou wtv é o seguinte:
Quando guardamos um user na base de dados, ele fica desde genero:
![image](https://user-images.githubusercontent.com/78921779/229309222-64187a54-db23-4096-9069-deeb348b8e17.png)
Precisamos de verificar se o que está certo, e verificar nas views.py a função novouser(request) nesta porção do código:
 ```      
if 'avatar' in request.FILES:
            avatar = request.FILES['avatar']
            fs = FileSystemStorage()
            filename = fs.save(avatar.name, avatar)
            uploaded_file_url = fs.url(filename)
            aluno.avatar = uploaded_file_url
            aluno.save()
        else:
            default_image = 'votacao/images/person_empty_holder.png'
            fs = FileSystemStorage()
            uploaded_file_url = fs.url(default_image)
            aluno.avatar = uploaded_file_url
            aluno.save()
```
aqui é onde guardamos o campo avatar do modelo aluno.

Já para visualizar a imagem, no dashboard (Perfil) sei que tenho lá o conteudo do campo avatar da BD através de {{ userPage.aluno.avatar.url }} (userpage é passado através de contexto, e como isto está no header.html não sei se ao chamar a função dashboard este contexto é passado para a view, mas , todo o resto dos dados adquiridos através de {{ userPage }} são acessiveis.

**Comment by bitilitos** [comment]
Já está resolvido esse pedaço, contudo tive que usar o código seguinte para que o header tivesse acesso ao utilizador.
def header(request):
    userid = request.user.username
    userPage = User.objects.get(username=userid)
    return render(request, 'votacao/header.html', {'userPage': userPage})

Só que pelos vistos a variável userPage só fica a dar na página do DashBoard, porque é lá que ela tb é chamada. 
Deve existir uma forma de conseguir chamar o utilizador logado no header.

Desta forma sempre que se muda de página o header perde a referencia ao user e não acede à página.

NOTA:
No settings.py tive que tirar a primeira base de caminho em '/votacao/static/media/' porque dá erro em linux. 
ficou assim: 
MEDIA_ROOT = os.path.join(BASE_DIR, 'votacao/static/media/')
Vejam se dá erro em Windows

![Screenshot from 2023-04-02 02-15-59](https://user-images.githubusercontent.com/78859268/229325479-00b2343a-3fcc-4f8d-9e20-9814fe3c74b2.png)

**Comment by bitilitos** [comment]
Usar {{user.aluno.avatar}} no template que ele vai buscar automaticamente
